GET http://localhost:8080/api/products?price=200


###

# POST http://localhost:8080/api/tutorials
# Content-Type: application/json

# {
#     "title":"tut2",
#     "description": "very good tutorial",
#     "published": true
# }

POST http://localhost:8080/api/products
Content-Type: application/json

{
    "id": 1000,
    "p_name":"test",
    "p_othername":"test other",
    "p_price": 2000,
    "p_size":"size test",
    "p_desc": "desc test",
    "p_desc2": "desc test2",
    "description": "hi",
    "water": "water test",
    "light": "light test",
    "pet": false,
    "imagename": "ABC"
}